$ChocoInstalls = @(
    '7zip',
    '7zip.commandline',
    'cmder',
    'curl',
    # 'Cygwin',
    # 'f.lux'
    'dotnet4.7.1',
    'dropbox',
    'Firefox',
    # 'foxitreader',
    'git',
    'git-credential-manager-for-windows',
    'git-credential-winstore',
    'gitextensions',
    'GoogleChrome',
    'sysinternals'
    # 'hub',
    'keypirinha',
    # 'nano',
    # 'nmap',
    # 'notepadplusplus',
    # 'nuget.commandline',
    # 'paint.net',
    # 'PDFCreator',
    # 'procexp',
    # 'putty',
    # 'python',
    # 'python3',
    # 'rvtools',
    # 'sharex',
    # 'sql-server-management-studio',
    # 'superputty',
    # 'terminals',
    # 'toolsroot',
    # 'virtualbox',
    # 'VirtualBox.ExtensionPack',
    # 'VirtualCloneDrive',
    'vlc',
    'win32diskimager',
    'windirstat',
    'winscp',
    # 'wireshark',
    # 'yumi',
    'visualstudiocode'
)
