# PowerShell Modules to install
$ModulesToBeInstalled = @(
    # 'Azure',
    # 'AzureAD',
    # 'AzureADPreview',
    # 'AzureRM',
    # 'Configuration',
    # 'CredentialManager',
    'dbatools'
    # 'EZOut',
    # 'HistoryPx',
    # 'InvokeBuild',
    # 'PackageManagement',
    # 'Pansies',
    # 'platyPS',
    # 'posh-git',
    # 'PowerLine',
    # 'PowerShellGet',
    # 'powershell-yaml',
    # 'psake',
    # 'PSCodeHealth',
    # 'PSDecode',
    # 'PSDepend',
    # 'PSGit',
    # 'PSGraph',
    # 'psmsgraph',
    # 'PSScriptAnalyzer',
    # 'SharePointPnPPowerShellOnline',
    # 'SnippetPx',
    # 'WinSCP',
    # 'OhMyPsh'
)